// Go version: go1.11.5

package token

import original "go/token"
import "scrigo"
import "reflect"

var Package = scrigo.Package{
	"ADD": scrigo.Constant(original.ADD, nil),
	"ADD_ASSIGN": scrigo.Constant(original.ADD_ASSIGN, nil),
	"AND": scrigo.Constant(original.AND, nil),
	"AND_ASSIGN": scrigo.Constant(original.AND_ASSIGN, nil),
	"AND_NOT": scrigo.Constant(original.AND_NOT, nil),
	"AND_NOT_ASSIGN": scrigo.Constant(original.AND_NOT_ASSIGN, nil),
	"ARROW": scrigo.Constant(original.ARROW, nil),
	"ASSIGN": scrigo.Constant(original.ASSIGN, nil),
	"BREAK": scrigo.Constant(original.BREAK, nil),
	"CASE": scrigo.Constant(original.CASE, nil),
	"CHAN": scrigo.Constant(original.CHAN, nil),
	"CHAR": scrigo.Constant(original.CHAR, nil),
	"COLON": scrigo.Constant(original.COLON, nil),
	"COMMA": scrigo.Constant(original.COMMA, nil),
	"COMMENT": scrigo.Constant(original.COMMENT, nil),
	"CONST": scrigo.Constant(original.CONST, nil),
	"CONTINUE": scrigo.Constant(original.CONTINUE, nil),
	"DEC": scrigo.Constant(original.DEC, nil),
	"DEFAULT": scrigo.Constant(original.DEFAULT, nil),
	"DEFER": scrigo.Constant(original.DEFER, nil),
	"DEFINE": scrigo.Constant(original.DEFINE, nil),
	"ELLIPSIS": scrigo.Constant(original.ELLIPSIS, nil),
	"ELSE": scrigo.Constant(original.ELSE, nil),
	"EOF": scrigo.Constant(original.EOF, nil),
	"EQL": scrigo.Constant(original.EQL, nil),
	"FALLTHROUGH": scrigo.Constant(original.FALLTHROUGH, nil),
	"FLOAT": scrigo.Constant(original.FLOAT, nil),
	"FOR": scrigo.Constant(original.FOR, nil),
	"FUNC": scrigo.Constant(original.FUNC, nil),
	"File": reflect.TypeOf(original.File{}),
	"FileSet": reflect.TypeOf(original.FileSet{}),
	"GEQ": scrigo.Constant(original.GEQ, nil),
	"GO": scrigo.Constant(original.GO, nil),
	"GOTO": scrigo.Constant(original.GOTO, nil),
	"GTR": scrigo.Constant(original.GTR, nil),
	"HighestPrec": scrigo.Constant(original.HighestPrec, nil),
	"IDENT": scrigo.Constant(original.IDENT, nil),
	"IF": scrigo.Constant(original.IF, nil),
	"ILLEGAL": scrigo.Constant(original.ILLEGAL, nil),
	"IMAG": scrigo.Constant(original.IMAG, nil),
	"IMPORT": scrigo.Constant(original.IMPORT, nil),
	"INC": scrigo.Constant(original.INC, nil),
	"INT": scrigo.Constant(original.INT, nil),
	"INTERFACE": scrigo.Constant(original.INTERFACE, nil),
	"LAND": scrigo.Constant(original.LAND, nil),
	"LBRACE": scrigo.Constant(original.LBRACE, nil),
	"LBRACK": scrigo.Constant(original.LBRACK, nil),
	"LEQ": scrigo.Constant(original.LEQ, nil),
	"LOR": scrigo.Constant(original.LOR, nil),
	"LPAREN": scrigo.Constant(original.LPAREN, nil),
	"LSS": scrigo.Constant(original.LSS, nil),
	"Lookup": original.Lookup,
	"LowestPrec": scrigo.Constant(original.LowestPrec, nil),
	"MAP": scrigo.Constant(original.MAP, nil),
	"MUL": scrigo.Constant(original.MUL, nil),
	"MUL_ASSIGN": scrigo.Constant(original.MUL_ASSIGN, nil),
	"NEQ": scrigo.Constant(original.NEQ, nil),
	"NOT": scrigo.Constant(original.NOT, nil),
	"NewFileSet": original.NewFileSet,
	"NoPos": scrigo.Constant(original.NoPos, nil),
	"OR": scrigo.Constant(original.OR, nil),
	"OR_ASSIGN": scrigo.Constant(original.OR_ASSIGN, nil),
	"PACKAGE": scrigo.Constant(original.PACKAGE, nil),
	"PERIOD": scrigo.Constant(original.PERIOD, nil),
	"Pos": reflect.TypeOf(original.Pos(int(0))),
	"Position": reflect.TypeOf(original.Position{}),
	"QUO": scrigo.Constant(original.QUO, nil),
	"QUO_ASSIGN": scrigo.Constant(original.QUO_ASSIGN, nil),
	"RANGE": scrigo.Constant(original.RANGE, nil),
	"RBRACE": scrigo.Constant(original.RBRACE, nil),
	"RBRACK": scrigo.Constant(original.RBRACK, nil),
	"REM": scrigo.Constant(original.REM, nil),
	"REM_ASSIGN": scrigo.Constant(original.REM_ASSIGN, nil),
	"RETURN": scrigo.Constant(original.RETURN, nil),
	"RPAREN": scrigo.Constant(original.RPAREN, nil),
	"SELECT": scrigo.Constant(original.SELECT, nil),
	"SEMICOLON": scrigo.Constant(original.SEMICOLON, nil),
	"SHL": scrigo.Constant(original.SHL, nil),
	"SHL_ASSIGN": scrigo.Constant(original.SHL_ASSIGN, nil),
	"SHR": scrigo.Constant(original.SHR, nil),
	"SHR_ASSIGN": scrigo.Constant(original.SHR_ASSIGN, nil),
	"STRING": scrigo.Constant(original.STRING, nil),
	"STRUCT": scrigo.Constant(original.STRUCT, nil),
	"SUB": scrigo.Constant(original.SUB, nil),
	"SUB_ASSIGN": scrigo.Constant(original.SUB_ASSIGN, nil),
	"SWITCH": scrigo.Constant(original.SWITCH, nil),
	"TYPE": scrigo.Constant(original.TYPE, nil),
	"Token": reflect.TypeOf(original.Token(int(0))),
	"UnaryPrec": scrigo.Constant(original.UnaryPrec, nil),
	"VAR": scrigo.Constant(original.VAR, nil),
	"XOR": scrigo.Constant(original.XOR, nil),
	"XOR_ASSIGN": scrigo.Constant(original.XOR_ASSIGN, nil),
}
