// Copyright (c) 2019 Open2b Software Snc. All rights reserved.
// https://www.open2b.com

// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package template

import (
	"os"
	"reflect"
)

var _os = Package{
	"O_RDONLY":          os.O_RDONLY,
	"O_WRONLY":          os.O_WRONLY,
	"O_RDWR":            os.O_RDWR,
	"O_APPEND":          os.O_APPEND,
	"O_CREATE":          os.O_CREATE,
	"O_EXCL":            os.O_EXCL,
	"O_SYNC":            os.O_SYNC,
	"O_TRUNC":           os.O_TRUNC,
	"SEEK_SET":          os.SEEK_SET,
	"SEEK_CUR":          os.SEEK_CUR,
	"SEEK_END":          os.SEEK_END,
	"PathSeparator":     os.PathSeparator,
	"PathListSeparator": os.PathListSeparator,
	"DevNull":           os.DevNull,
	"ErrInvalid":        &os.ErrInvalid,
	"ErrPermission":     &os.ErrPermission,
	"ErrExist":          &os.ErrExist,
	"ErrNotExist":       &os.ErrNotExist,
	"ErrClosed":         &os.ErrClosed,
	"ErrNoDeadline":     &os.ErrNoDeadline,
	"Stdin":             &os.Stdin,
	"Stdout":            &os.Stdout,
	"Stderr":            &os.Stderr,
	"Args":              &os.Args,
	"Chdir":             os.Chdir,
	"Chmod":             os.Chmod,
	"Chown":             os.Chown,
	"Chtimes":           os.Chtimes,
	"Clearenv":          os.Clearenv,
	"Create":            os.Create,
	"Environ":           os.Environ,
	"Executable":        os.Executable,
	"Exit":              os.Exit,
	"Expand":            os.Expand,
	"ExpandEnv":         os.ExpandEnv,
	"FindProcess":       os.FindProcess,
	"Getegid":           os.Getegid,
	"Getenv":            os.Getenv,
	"Geteuid":           os.Geteuid,
	"Getgid":            os.Getgid,
	"Getgroups":         os.Getgroups,
	"Getpagesize":       os.Getpagesize,
	"Getpid":            os.Getpid,
	"Getppid":           os.Getppid,
	"Getuid":            os.Getuid,
	"Getwd":             os.Getwd,
	"Hostname":          os.Hostname,
	"IsExist":           os.IsExist,
	"IsNotExist":        os.IsNotExist,
	"IsPathSeparator":   os.IsPathSeparator,
	"IsPermission":      os.IsPermission,
	"IsTimeout":         os.IsTimeout,
	"Lchown":            os.Lchown,
	"Link":              os.Link,
	"LookupEnv":         os.LookupEnv,
	"Lstat":             os.Lstat,
	"Mkdir":             os.Mkdir,
	"MkdirAll":          os.MkdirAll,
	"NewFile":           os.NewFile,
	"NewSyscallError":   os.NewSyscallError,
	"Open":              os.Open,
	"OpenFile":          os.OpenFile,
	"Pipe":              os.Pipe,
	"Readlink":          os.Readlink,
	"Remove":            os.Remove,
	"RemoveAll":         os.RemoveAll,
	"Rename":            os.Rename,
	"SameFile":          os.SameFile,
	"Setenv":            os.Setenv,
	"StartProcess":      os.StartProcess,
	"Stat":              os.Stat,
	"Symlink":           os.Symlink,
	"TempDir":           os.TempDir,
	"Truncate":          os.Truncate,
	"Unsetenv":          os.Unsetenv,
	"UserCacheDir":      os.UserCacheDir,
	"File":              reflect.TypeOf(os.File{}),
	"FileInfo":          reflect.TypeOf((*os.FileInfo)(nil)).Elem(),
	"FileMode":          reflect.TypeOf(os.FileMode(0)),
}
