// Go version: go1.11.5

package types

import original "go/types"
import "scrigo"
import "reflect"

var Package = scrigo.Package{
	"Array": reflect.TypeOf(original.Array{}),
	"AssertableTo": original.AssertableTo,
	"AssignableTo": original.AssignableTo,
	"Basic": reflect.TypeOf(original.Basic{}),
	"BasicInfo": reflect.TypeOf(original.BasicInfo(int(0))),
	"BasicKind": reflect.TypeOf(original.BasicKind(int(0))),
	"Bool": scrigo.Constant(original.Bool, nil),
	"Builtin": reflect.TypeOf(original.Builtin{}),
	"Byte": scrigo.Constant(original.Byte, nil),
	"Chan": reflect.TypeOf(original.Chan{}),
	"ChanDir": reflect.TypeOf(original.ChanDir(int(0))),
	"Checker": reflect.TypeOf(original.Checker{}),
	"Comparable": original.Comparable,
	"Complex128": scrigo.Constant(original.Complex128, nil),
	"Complex64": scrigo.Constant(original.Complex64, nil),
	"Config": reflect.TypeOf(original.Config{}),
	"Const": reflect.TypeOf(original.Const{}),
	"ConvertibleTo": original.ConvertibleTo,
	"DefPredeclaredTestFuncs": original.DefPredeclaredTestFuncs,
	"Default": original.Default,
	"Error": reflect.TypeOf(original.Error{}),
	"Eval": original.Eval,
	"ExprString": original.ExprString,
	"FieldVal": scrigo.Constant(original.FieldVal, nil),
	"Float32": scrigo.Constant(original.Float32, nil),
	"Float64": scrigo.Constant(original.Float64, nil),
	"Func": reflect.TypeOf(original.Func{}),
	"Id": original.Id,
	"Identical": original.Identical,
	"IdenticalIgnoreTags": original.IdenticalIgnoreTags,
	"Implements": original.Implements,
	"ImportMode": reflect.TypeOf(original.ImportMode(int(0))),
	"Importer": reflect.TypeOf((*original.Importer)(nil)).Elem(),
	"ImporterFrom": reflect.TypeOf((*original.ImporterFrom)(nil)).Elem(),
	"Info": reflect.TypeOf(original.Info{}),
	"Initializer": reflect.TypeOf(original.Initializer{}),
	"Int": scrigo.Constant(original.Int, nil),
	"Int16": scrigo.Constant(original.Int16, nil),
	"Int32": scrigo.Constant(original.Int32, nil),
	"Int64": scrigo.Constant(original.Int64, nil),
	"Int8": scrigo.Constant(original.Int8, nil),
	"Interface": reflect.TypeOf(original.Interface{}),
	"Invalid": scrigo.Constant(original.Invalid, nil),
	"IsBoolean": scrigo.Constant(original.IsBoolean, nil),
	"IsComplex": scrigo.Constant(original.IsComplex, nil),
	"IsConstType": scrigo.Constant(original.IsConstType, nil),
	"IsFloat": scrigo.Constant(original.IsFloat, nil),
	"IsInteger": scrigo.Constant(original.IsInteger, nil),
	"IsInterface": original.IsInterface,
	"IsNumeric": scrigo.Constant(original.IsNumeric, nil),
	"IsOrdered": scrigo.Constant(original.IsOrdered, nil),
	"IsString": scrigo.Constant(original.IsString, nil),
	"IsUnsigned": scrigo.Constant(original.IsUnsigned, nil),
	"IsUntyped": scrigo.Constant(original.IsUntyped, nil),
	"Label": reflect.TypeOf(original.Label{}),
	"LookupFieldOrMethod": original.LookupFieldOrMethod,
	"Map": reflect.TypeOf(original.Map{}),
	"MethodExpr": scrigo.Constant(original.MethodExpr, nil),
	"MethodSet": reflect.TypeOf(original.MethodSet{}),
	"MethodVal": scrigo.Constant(original.MethodVal, nil),
	"MissingMethod": original.MissingMethod,
	"Named": reflect.TypeOf(original.Named{}),
	"NewArray": original.NewArray,
	"NewChan": original.NewChan,
	"NewChecker": original.NewChecker,
	"NewConst": original.NewConst,
	"NewField": original.NewField,
	"NewFunc": original.NewFunc,
	"NewInterface": original.NewInterface,
	"NewInterfaceType": original.NewInterfaceType,
	"NewLabel": original.NewLabel,
	"NewMap": original.NewMap,
	"NewMethodSet": original.NewMethodSet,
	"NewNamed": original.NewNamed,
	"NewPackage": original.NewPackage,
	"NewParam": original.NewParam,
	"NewPkgName": original.NewPkgName,
	"NewPointer": original.NewPointer,
	"NewScope": original.NewScope,
	"NewSignature": original.NewSignature,
	"NewSlice": original.NewSlice,
	"NewStruct": original.NewStruct,
	"NewTuple": original.NewTuple,
	"NewTypeName": original.NewTypeName,
	"NewVar": original.NewVar,
	"Nil": reflect.TypeOf(original.Nil{}),
	"Object": reflect.TypeOf((*original.Object)(nil)).Elem(),
	"ObjectString": original.ObjectString,
	"Package": reflect.TypeOf(original.Package{}),
	"PkgName": reflect.TypeOf(original.PkgName{}),
	"Pointer": reflect.TypeOf(original.Pointer{}),
	"Qualifier": reflect.TypeOf((original.Qualifier)(nil)),
	"RecvOnly": scrigo.Constant(original.RecvOnly, nil),
	"RelativeTo": original.RelativeTo,
	"Rune": scrigo.Constant(original.Rune, nil),
	"Scope": reflect.TypeOf(original.Scope{}),
	"Selection": reflect.TypeOf(original.Selection{}),
	"SelectionKind": reflect.TypeOf(original.SelectionKind(int(0))),
	"SelectionString": original.SelectionString,
	"SendOnly": scrigo.Constant(original.SendOnly, nil),
	"SendRecv": scrigo.Constant(original.SendRecv, nil),
	"Signature": reflect.TypeOf(original.Signature{}),
	"Sizes": reflect.TypeOf((*original.Sizes)(nil)).Elem(),
	"SizesFor": original.SizesFor,
	"Slice": reflect.TypeOf(original.Slice{}),
	"StdSizes": reflect.TypeOf(original.StdSizes{}),
	"String": scrigo.Constant(original.String, nil),
	"Struct": reflect.TypeOf(original.Struct{}),
	"Tuple": reflect.TypeOf(original.Tuple{}),
	"Typ": &original.Typ,
	"Type": reflect.TypeOf((*original.Type)(nil)).Elem(),
	"TypeAndValue": reflect.TypeOf(original.TypeAndValue{}),
	"TypeName": reflect.TypeOf(original.TypeName{}),
	"TypeString": original.TypeString,
	"Uint": scrigo.Constant(original.Uint, nil),
	"Uint16": scrigo.Constant(original.Uint16, nil),
	"Uint32": scrigo.Constant(original.Uint32, nil),
	"Uint64": scrigo.Constant(original.Uint64, nil),
	"Uint8": scrigo.Constant(original.Uint8, nil),
	"Uintptr": scrigo.Constant(original.Uintptr, nil),
	"Universe": &original.Universe,
	"Unsafe": &original.Unsafe,
	"UnsafePointer": scrigo.Constant(original.UnsafePointer, nil),
	"UntypedBool": scrigo.Constant(original.UntypedBool, nil),
	"UntypedComplex": scrigo.Constant(original.UntypedComplex, nil),
	"UntypedFloat": scrigo.Constant(original.UntypedFloat, nil),
	"UntypedInt": scrigo.Constant(original.UntypedInt, nil),
	"UntypedNil": scrigo.Constant(original.UntypedNil, nil),
	"UntypedRune": scrigo.Constant(original.UntypedRune, nil),
	"UntypedString": scrigo.Constant(original.UntypedString, nil),
	"Var": reflect.TypeOf(original.Var{}),
	"WriteExpr": original.WriteExpr,
	"WriteSignature": original.WriteSignature,
	"WriteType": original.WriteType,
}
