// Go version: go1.11.5

package math

import original "math"
import "scrigo"

var Package = scrigo.Package{
	"Abs": original.Abs,
	"Acos": original.Acos,
	"Acosh": original.Acosh,
	"Asin": original.Asin,
	"Asinh": original.Asinh,
	"Atan": original.Atan,
	"Atan2": original.Atan2,
	"Atanh": original.Atanh,
	"Cbrt": original.Cbrt,
	"Ceil": original.Ceil,
	"Copysign": original.Copysign,
	"Cos": original.Cos,
	"Cosh": original.Cosh,
	"Dim": original.Dim,
	"E": scrigo.Constant(original.E, nil),
	"Erf": original.Erf,
	"Erfc": original.Erfc,
	"Erfcinv": original.Erfcinv,
	"Erfinv": original.Erfinv,
	"Exp": original.Exp,
	"Exp2": original.Exp2,
	"Expm1": original.Expm1,
	"Float32bits": original.Float32bits,
	"Float32frombits": original.Float32frombits,
	"Float64bits": original.Float64bits,
	"Float64frombits": original.Float64frombits,
	"Floor": original.Floor,
	"Frexp": original.Frexp,
	"Gamma": original.Gamma,
	"Hypot": original.Hypot,
	"Ilogb": original.Ilogb,
	"Inf": original.Inf,
	"IsInf": original.IsInf,
	"IsNaN": original.IsNaN,
	"J0": original.J0,
	"J1": original.J1,
	"Jn": original.Jn,
	"Ldexp": original.Ldexp,
	"Lgamma": original.Lgamma,
	"Ln10": scrigo.Constant(original.Ln10, nil),
	"Ln2": scrigo.Constant(original.Ln2, nil),
	"Log": original.Log,
	"Log10": original.Log10,
	"Log10E": scrigo.Constant(original.Log10E, nil),
	"Log1p": original.Log1p,
	"Log2": original.Log2,
	"Log2E": scrigo.Constant(original.Log2E, nil),
	"Logb": original.Logb,
	"Max": original.Max,
	"MaxFloat32": scrigo.Constant(original.MaxFloat32, nil),
	"MaxFloat64": scrigo.Constant(original.MaxFloat64, nil),
	"MaxInt16": scrigo.Constant(original.MaxInt16, nil),
	"MaxInt32": scrigo.Constant(original.MaxInt32, nil),
	"MaxInt64": scrigo.Constant(original.MaxInt64, nil),
	"MaxInt8": scrigo.Constant(original.MaxInt8, nil),
	"MaxUint16": scrigo.Constant(original.MaxUint16, nil),
	"MaxUint32": scrigo.Constant(original.MaxUint32, nil),
	"MaxUint64": scrigo.Constant(uint64(original.MaxUint64), nil),
	"MaxUint8": scrigo.Constant(original.MaxUint8, nil),
	"Min": original.Min,
	"MinInt16": scrigo.Constant(original.MinInt16, nil),
	"MinInt32": scrigo.Constant(original.MinInt32, nil),
	"MinInt64": scrigo.Constant(original.MinInt64, nil),
	"MinInt8": scrigo.Constant(original.MinInt8, nil),
	"Mod": original.Mod,
	"Modf": original.Modf,
	"NaN": original.NaN,
	"Nextafter": original.Nextafter,
	"Nextafter32": original.Nextafter32,
	"Phi": scrigo.Constant(original.Phi, nil),
	"Pi": scrigo.Constant(original.Pi, nil),
	"Pow": original.Pow,
	"Pow10": original.Pow10,
	"Remainder": original.Remainder,
	"Round": original.Round,
	"RoundToEven": original.RoundToEven,
	"Signbit": original.Signbit,
	"Sin": original.Sin,
	"Sincos": original.Sincos,
	"Sinh": original.Sinh,
	"SmallestNonzeroFloat32": scrigo.Constant(original.SmallestNonzeroFloat32, nil),
	"SmallestNonzeroFloat64": scrigo.Constant(original.SmallestNonzeroFloat64, nil),
	"Sqrt": original.Sqrt,
	"Sqrt2": scrigo.Constant(original.Sqrt2, nil),
	"SqrtE": scrigo.Constant(original.SqrtE, nil),
	"SqrtPhi": scrigo.Constant(original.SqrtPhi, nil),
	"SqrtPi": scrigo.Constant(original.SqrtPi, nil),
	"Tan": original.Tan,
	"Tanh": original.Tanh,
	"Trunc": original.Trunc,
	"Y0": original.Y0,
	"Y1": original.Y1,
	"Yn": original.Yn,
}
