// Go version: go1.11.5

package time

import original "time"
import "scrigo"
import "reflect"

var Package = scrigo.Package{
	"ANSIC": scrigo.Constant(original.ANSIC, nil),
	"After": original.After,
	"AfterFunc": original.AfterFunc,
	"April": scrigo.Constant(original.April, nil),
	"August": scrigo.Constant(original.August, nil),
	"Date": original.Date,
	"December": scrigo.Constant(original.December, nil),
	"Duration": reflect.TypeOf(original.Duration(int64(0))),
	"February": scrigo.Constant(original.February, nil),
	"FixedZone": original.FixedZone,
	"Friday": scrigo.Constant(original.Friday, nil),
	"Hour": scrigo.Constant(original.Hour, nil),
	"January": scrigo.Constant(original.January, nil),
	"July": scrigo.Constant(original.July, nil),
	"June": scrigo.Constant(original.June, nil),
	"Kitchen": scrigo.Constant(original.Kitchen, nil),
	"LoadLocation": original.LoadLocation,
	"LoadLocationFromTZData": original.LoadLocationFromTZData,
	"Local": &original.Local,
	"Location": reflect.TypeOf(original.Location{}),
	"March": scrigo.Constant(original.March, nil),
	"May": scrigo.Constant(original.May, nil),
	"Microsecond": scrigo.Constant(original.Microsecond, nil),
	"Millisecond": scrigo.Constant(original.Millisecond, nil),
	"Minute": scrigo.Constant(original.Minute, nil),
	"Monday": scrigo.Constant(original.Monday, nil),
	"Month": reflect.TypeOf(original.Month(int(0))),
	"Nanosecond": scrigo.Constant(original.Nanosecond, nil),
	"NewTicker": original.NewTicker,
	"NewTimer": original.NewTimer,
	"November": scrigo.Constant(original.November, nil),
	"Now": original.Now,
	"October": scrigo.Constant(original.October, nil),
	"Parse": original.Parse,
	"ParseDuration": original.ParseDuration,
	"ParseError": reflect.TypeOf(original.ParseError{}),
	"ParseInLocation": original.ParseInLocation,
	"RFC1123": scrigo.Constant(original.RFC1123, nil),
	"RFC1123Z": scrigo.Constant(original.RFC1123Z, nil),
	"RFC3339": scrigo.Constant(original.RFC3339, nil),
	"RFC3339Nano": scrigo.Constant(original.RFC3339Nano, nil),
	"RFC822": scrigo.Constant(original.RFC822, nil),
	"RFC822Z": scrigo.Constant(original.RFC822Z, nil),
	"RFC850": scrigo.Constant(original.RFC850, nil),
	"RubyDate": scrigo.Constant(original.RubyDate, nil),
	"Saturday": scrigo.Constant(original.Saturday, nil),
	"Second": scrigo.Constant(original.Second, nil),
	"September": scrigo.Constant(original.September, nil),
	"Since": original.Since,
	"Sleep": original.Sleep,
	"Stamp": scrigo.Constant(original.Stamp, nil),
	"StampMicro": scrigo.Constant(original.StampMicro, nil),
	"StampMilli": scrigo.Constant(original.StampMilli, nil),
	"StampNano": scrigo.Constant(original.StampNano, nil),
	"Sunday": scrigo.Constant(original.Sunday, nil),
	"Thursday": scrigo.Constant(original.Thursday, nil),
	"Tick": original.Tick,
	"Ticker": reflect.TypeOf(original.Ticker{}),
	"Time": reflect.TypeOf(original.Time{}),
	"Timer": reflect.TypeOf(original.Timer{}),
	"Tuesday": scrigo.Constant(original.Tuesday, nil),
	"UTC": &original.UTC,
	"Unix": original.Unix,
	"UnixDate": scrigo.Constant(original.UnixDate, nil),
	"Until": original.Until,
	"Wednesday": scrigo.Constant(original.Wednesday, nil),
	"Weekday": reflect.TypeOf(original.Weekday(int(0))),
}
